apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
    name: wallabag-dev-cluster-2026
    namespace: wallabag
spec:
    retentionPolicy: 7d
    configuration:
        destinationPath: ENC[AES256_GCM,data:lu9AyzxKquS2lI54vq/kd0qFboPHftLW1+oMj2NNEn3D/rYhpnMDhpfr9DyAzOtn9zip9Ppn9JsiAgs/4gQ=,iv:Ba/sUIcqr92PNnBZ65HmafCVHjJMXrfpxxxDWegS5MM=,tag:BxyNSRMWz7f+N0yyvyBcBQ==,type:str]
        s3Credentials:
            accessKeyId:
                name: aws-creds
                key: AWS_ACCESS_KEY_ID
            secretAccessKey:
                name: aws-creds
                key: AWS_SECRET_ACCESS_KEY
        wal:
            compression: gzip
        data:
            compression: ENC[AES256_GCM,data:5DSNlA==,iv:G4uzbbi0OzOlWnMJwOPW1BeRqRMcd9FoDKwz/cpyDE8=,tag:gGySjgxBZtazHhmWCd0PBw==,type:str]
sops:
    age:
        - recipient: age1vml3vk5uzyztj96qgz7n0a6w8ynvtmxfarkp0jdl0hvcj003895qcp6z09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dWxsRW9WdGpaUVlSM3Fa
            QlJVZXBMdkF2NkhJNnZrTEVDQUt0aTgrV21FCjVxSm9pK0tTbDFKcUFFQ0dZM29S
            bXFFVDRBVlRvYUVaU01CMHVDdzFlT1kKLS0tIHl3L1BuK3JIaEorY2R6WXdDcEk4
            dmowNWVyV1kwVTIxMExXemdwS0tLNEEK1441syTxbvOn+A+QbsoVrdHOa/2UzkaG
            O3H6KeX1wqrBJv/Kn8wwTBkx38Zd8P9mORp/Jv/5gwoJFgx4iEHrHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T22:59:52Z"
    mac: ENC[AES256_GCM,data:KR7UsDPy00RXw/JGn9sZ7yOdDrO1MAp4bAj0NMCSyKOSU4VBZNSJLIKLlFVpWssupWoM7xIUkXBdDo60w43Hm6QF9TzSdoIfcGD7m8kXxsj9/9hPyyhodQh93ZK9/e4LhaEJh9oB/ySz89SpQ22u21gfCeB1GR+bnIfF1r27Mng=,iv:JmbGGDIySfq1vjN1ei53yRS428qKvad56qGbQYZqLCg=,tag:cZdMhQd9vU+X1hX5trH85A==,type:str]
    encrypted_regex: ^(data|destinationPath)$
    version: 3.10.2
