---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack-webhook
  namespace: monitoring
  labels:
    app: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: slack-webhook
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: metrics_webhook_dev
        property: credential
