---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
  labels:
    app: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafana-admin-credentials
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: grafana-admin
        property: user
    - secretKey: admin-password
      remoteRef:
        key: grafana-admin
        property: password
