---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  chart:
    spec:
      chart: external-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
      version: 1.0.0

  interval: 1m0s
  releaseName: external-secrets
  targetNamespace: external-secrets
  values:
    global:
      nodeSelector:
        node: "worker"
    image:
      pullPolicy: Always
    log:
      level: info
      timeEncoding: epoch
    installCRDs: true
    crds:
      createClusterExternalSecret: true
      createClusterSecretStore: true
      createPushSecret: true
    webhook:
      image:
        pullPolicy: Always
    certController:
      image:
        pullPolicy: Always
    serviceMonitor:
      enabled: false
      namespace: "monitoring"
    grafanaDashboard:
      enabled: false
    replicaCount: 1
    revisionHistoryLimit: 15
