# _lib/secrets/external-secrets/helmrelease.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  chart:
    spec:
      chart: external-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
      version: 0.19.2
  interval: 1m0s
  releaseName: external-secrets
  targetNamespace: external-secrets
  values:
    global:
      nodeSelector:
        node: "worker"
    log:
      level: info
      timeEncoding: epoch
    installCRDs: true
    crds:
      createClusterExternalSecret: true
      createClusterSecretStore: true
      createPushSecret: true
    serviceMonitor:
      enabled: false
      namespace: "monitoring"
    grafanaDashboard:
      enabled: false
    replicaCount: 1
    revisionHistoryLimit: 15
    extraVolumes:
      - name: internal-ca
        configMap:
          name: homelab-internal-ca-bundle
    extraVolumeMounts:
      - name: internal-ca
        mountPath: /etc/ssl/certs/homelab-internal-ca.crt
        subPath: ca-certificates.crt
        readOnly: true

