---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hcloud-csi-token
  namespace: kube-system
  labels:
    app: hcloud-csi
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: hcloud-csi-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: hcloud_api_token
        property: credential
