---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../cert-manager
  - ../cloudnativepg
  - ../kyverno
  - ../mariadb-operator
  - ../redis-operator
  - ../renovate
  - ../hcloud-ccm
