---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-data
  namespace: obsidian-livesync
  labels:
    app.kubernetes.io/name: obsidian-livesync
    app.kubernetes.io/instance: obsidian-livesync-${ENVIRONMENT}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
