---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: couchdb-creds
  namespace: obsidian-livesync
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: couchdb-creds
    creationPolicy: Owner
  data:
    - secretKey: COUCHDB_USER
      remoteRef:
        key: obsidian-livesync_${ENVIRONMENT}
        property: username
    - secretKey: COUCHDB_PASSWORD
      remoteRef:
        key: obsidian-livesync_${ENVIRONMENT}
        property: password
