---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: networking
  labels:
    app: networking
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudflare-api-token
    creationPolicy: Owner
  data:
    - secretKey: CF_API_TOKEN
      remoteRef:
        key: cloudflare_api_token
        property: credential
