---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-cloudflare
  namespace: flux-system
spec:
  chart:
    spec:
      chart: external-dns
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      version: 1.19.0
  interval: 15m
  maxHistory: 3
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  releaseName: external-dns-cloudflare
  targetNamespace: networking
  values:
    fullnameOverride: external-dns-cloudflare
    logLevel: info
    provider:
      name: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-token
            key: CF_API_TOKEN
    policy: upsert-only
    sources: ["ingress", "service", "gateway-httproute"]
    txtOwnerId: hetzner
    txtPrefix: k8s.
    domainFilters: ["home-0ps.com"]
    extraArgs:
      - --ignore-ingress-tls-spec
