apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: wallabag-dev-cluster-backup
  namespace: wallabag
spec:
  retentionPolicy: 7d
  configuration:
    destinationPath: s3://wallabag-dev-backups/
    s3Credentials:
      accessKeyId:
        name: aws-creds
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: aws-creds
        key: AWS_SECRET_ACCESS_KEY
    wal:
      compression: gzip
    data:
      compression: gzip
