apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword-connect
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: connect
      sourceRef:
        kind: HelmRepository
        name: onepassword-connect
      version: "2.0.5"
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  targetNamespace: onepassword
  values:
    connect:
      api:
        name: connect-api
        imageRepository: 1password/connect-api
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        logLevel: info
        serviceMonitor:
          enabled: false
          interval: 30s
          path: "/metrics"
      sync:
        name: connect-sync
        imageRepository: 1password/connect-sync
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
      serviceAccount:
        create: true
      credentialsName: onepassword-connect-secret
      credentialsKey: 1password-credentials.json
      imagePullPolicy: Always
      tls:
        enabled: true
        secret: op-connect-tls
      nodeSelector:
        node: "worker"
    operator:
      create: true
      imagePullPolicy: Always
      autoRestart: true
      pollingInterval: 600
      logLevel: error
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 150m
          memory: 128Mi
      nodeSelector:
        node: "worker"
      token:
        name: onepassword-token
        key: token
