---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-data
  namespace: freshrss
  labels:
    app.kubernetes.io/name: freshrss
    app.kubernetes.io/instance: freshrss-${ENVIRONMENT}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
