---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: kyverno
      version: 3.5.0
      sourceRef:
        name: kyverno
        kind: HelmRepository
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  targetNamespace: kyverno
  values:
    config:
      excludeKyvernoNamespace: true
      resourceFiltersExcludeNamespaces:
        - kube-system
        - kube-public
        - kube-node-lease
        - flux-system
        - security
        - storage
        - networking
        - database
        - cert-manager
        - external-secrets
        - monitoring
        - onepassword
        - renovate
        - mariadb
        - redis
    admissionController:
      container:
        image:
          pullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
      initContainer:
        image:
          pullPolicy: Always
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
    backgroundController:
      container:
        image:
          pullPolicy: Always
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 256Mi
    cleanupController:
      container:
        image:
          pullPolicy: Always
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 256Mi
    reportsController:
      container:
        image:
          defaultRegistry: reg.kyverno.io
          repository: kyverno/reports-controller
          pullPolicy: Always

        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 256Mi
