apiVersion: v1
data:
    cloudflare-token: ENC[AES256_GCM,data:biHNBBMBbH68qNAaRM0KjHtd21NexdKzGgX+TyvAMNEy00Otp1lNMnRrO73j88idR+zLXHNvSH0=,iv:yGoJFNVhBZmU+9yXSaw8TJfyPJWuUaeWODnN6i0pWPU=,tag:ijukI8MLhDDztZ92Sa27PA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cloudflare-token-secret
    namespace: cert-manager
sops:
    age:
        - recipient: age1vml3vk5uzyztj96qgz7n0a6w8ynvtmxfarkp0jdl0hvcj003895qcp6z09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUys0T05XcmtNRFJsMmtJ
            b05LU0dZU3AyVUZ2RTFKMGQ2VWJXVWZvUWtRCjFwemlqYjVqOTdsS0s1UHlWaTk4
            QWl5MmtyajNhNXljOThuNzdEK2dxRG8KLS0tIExhMzdKNklPUHJnUlFhalNyV2RF
            bmlGMUMySHdpOG50ZlcrRjBvTi9nOUUKQa7rfp4qvXrnhIwQZFwc+ZuI/BZeS/D0
            q5RPCKWtot1veZwqxKoDHZeAjT1wJFCLRKhDoLMZLz5PyntvVMIxWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T02:29:32Z"
    mac: ENC[AES256_GCM,data:xWCTr9mbxXph/bvYAajgZdJPt5s6oln3o/f3b0jY0JcZriBvdzAzfRcVvaVGoyexl9yw97+0Y2CBui9f8WBi4vwEqU4rFekpfn+QWLcXPve9MUttThONT4HOTVNjeirPI9tYZFtVW3/t4QvvV/DzbKBayix0pz8PU6w3N75Lv1I=,iv:1a5Sg28Z13oO4Z690AFoI8eFkOmHB3gWaxUJLRjP+Dg=,tag:Zdcz4+B8BaBLrttQi0fVGg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
