---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: homelab-internal-ca-bundle
spec:
  sources:
    - secret:
        name: homelab-internal-ca-keypair
        key: tls.crt
  target:
    configMap:
      key: ca-certificates.crt
    namespaceSelector:
      matchLabels:
        homelab-internal-ca/inject: "true"
