---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: wallabag-${ENVIRONMENT}-cluster
  namespace: wallabag
  labels:
    app: "wallabag"
    node: "worker"
    env: "${ENVIRONMENT}"
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  postgresql:
    pg_hba:
      - hostssl wallabag wallabag 10.43.0.0/16 scram-sha-256
    parameters:
      "pgaudit.log": "all, -misc"
      "pgaudit.log_catalog": "off"
      "pgaudit.log_parameter": "on"
      "pgaudit.log_relation": "on"
  instances: 3
  superuserSecret:
    name: wallabag-db-creds
  storage:
    size: 20Gi
    storageClass: local-path
  walStorage:
    size: 5Gi
    storageClass: local-path
  bootstrap:
    recovery:
      source: wallabag-prod-cluster
      database: wallabag
      owner: wallabag
      secret:
        name: wallabag-db-creds
      recoveryTarget:
        backupID: "20260502T220002"
        targetImmediate: true
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: wallabag-dev-cluster-2026
  externalClusters:
  - name: wallabag-prod-cluster
    plugin:
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: wallabag-dev-cluster-backup
        serverName: wallabag-prod-cluster
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: wallabag-dev-backup
  namespace: wallabag
spec:
  schedule: "0 0 * * *"
  cluster:
    name: wallabag-dev-cluster
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  immediate: true
