apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
    name: wallabag-dev-cluster-2026
    namespace: wallabag
spec:
    retentionPolicy: 7d
    configuration:
        destinationPath: ENC[AES256_GCM,data:/7khIgd5WBrSqNdgYeUllhUxi18JvHAkzMuNx5Y3ES9W/B34571aIRVJC6S6m1kDIcCuWkPy/6ZSQwihzNw=,iv:7Onp4ixuzcYyRZCizJUASWyh6Uu9Bl55QEEAYPP3zQA=,tag:G6hVg9b0afezwofFlCojBQ==,type:str]
        s3Credentials:
            accessKeyId:
                name: aws-creds
                key: AWS_ACCESS_KEY_ID
            secretAccessKey:
                name: aws-creds
                key: AWS_SECRET_ACCESS_KEY
        wal:
            compression: gzip
        data:
            compression: ENC[AES256_GCM,data:5DSNlA==,iv:G4uzbbi0OzOlWnMJwOPW1BeRqRMcd9FoDKwz/cpyDE8=,tag:gGySjgxBZtazHhmWCd0PBw==,type:str]
sops:
    age:
        - recipient: age1vml3vk5uzyztj96qgz7n0a6w8ynvtmxfarkp0jdl0hvcj003895qcp6z09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dWxsRW9WdGpaUVlSM3Fa
            QlJVZXBMdkF2NkhJNnZrTEVDQUt0aTgrV21FCjVxSm9pK0tTbDFKcUFFQ0dZM29S
            bXFFVDRBVlRvYUVaU01CMHVDdzFlT1kKLS0tIHl3L1BuK3JIaEorY2R6WXdDcEk4
            dmowNWVyV1kwVTIxMExXemdwS0tLNEEK1441syTxbvOn+A+QbsoVrdHOa/2UzkaG
            O3H6KeX1wqrBJv/Kn8wwTBkx38Zd8P9mORp/Jv/5gwoJFgx4iEHrHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T05:16:07Z"
    mac: ENC[AES256_GCM,data:a6kizSlFBqLzHj2Q3VlCfj0fymWZXz+EBmmfuqIgWfpEEvo3G4xNgfamXNYHmhXNQPCPGIqqP1YSWZ3zLpQnNzv2E5ffUAB2onF2H7pM7HrIRWZ/fINoE+GBT4XLAm3yzRS1YDJjBfi4+G8nJJoIXUkoXUNruH8OboqLAhnES38=,iv:PIYWuGOv8P+a3jvAXkH9K5IVRHmuijKJfy8y9I8JjT4=,tag:Bbv7HsyX5ipQMFWmqlBVZA==,type:str]
    encrypted_regex: ^(data|destinationPath)$
    version: 3.10.2
