apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
    name: "wallabag-{ENVIRONMENT}-cluster-2026"
    namespace: wallabag
spec:
    retentionPolicy: 7d
    configuration:
        destinationPath: ENC[AES256_GCM,data:Awcbg0eM/ENQytchI8rPrzHweIbBn9i4ebLWfPABT51vcqf1qrqUXNzE9A5orlj+diaegQswUj8aFOnlwfQ=,iv:+9bptavPiLNaWEHsySftZA/5sZ9x0HCv+xwVrZV+Hn8=,tag:DG+dFZoCUL94Y5Lb57cnXw==,type:str]
        s3Credentials:
            accessKeyId:
                name: aws-creds
                key: AWS_ACCESS_KEY_ID
            secretAccessKey:
                name: aws-creds
                key: AWS_SECRET_ACCESS_KEY
        wal:
            compression: gzip
        data:
            compression: ENC[AES256_GCM,data:fTXfRw==,iv:MpO6wsOw2tnVGte1UE483KPZUqzTVPrpNhstLrRyj0E=,tag:RVCThEEA3VGCWNtDOv5bjw==,type:str]
sops:
    age:
        - recipient: age1vml3vk5uzyztj96qgz7n0a6w8ynvtmxfarkp0jdl0hvcj003895qcp6z09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwK2h3Qkx6TWYzL050d2tO
            cFlaYmk3dnVRbEZVdTBOUDhXcHFhd2tuUEdBCmFvYm5JMDI5VVg3cUl5YXdUZG9q
            NHNPMmoxblQzM2hyNnh1Z2Vwek5QYTAKLS0tIHZTTFFSQ0h6WHh2WFlpNEE4VGti
            R283eTJjWkFtQW9kWWlXT2N1SUFOYTgK0WObcESHP1BMLqjkjmR0745IF4fxANNR
            3LQfvrFvCaNMUdUnJHvZrc0c14oDaPRUuhX90pq3yCOURRA+0i3xOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T00:17:20Z"
    mac: ENC[AES256_GCM,data:AvuBOlF/WNxYmDLBKq7LFc8/uZGH/Sp2At4kh2LPkEK8XfF0Fj0k7LQlo0jj59rz1vZYZ3WUj53+V/hC8Kt67Q5l/Pbgd5zu/A//7JguPMTrkGrn0xMCQfIHjCn8/DF+SCcBaDVZDb4ASKl7UB6vyZ+V3nMmdgUGs28uczAiy0A=,iv:bk+b+7ZgFqywacqhigmbOWWgRz55BlExKVya4oQfGfs=,tag:5lquXYkCI5K4203P4vAx5w==,type:str]
    encrypted_regex: ^(data|destinationPath)$
    version: 3.10.2
