apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
    name: wallabag-dev-cluster-backup
    namespace: wallabag
spec:
    retentionPolicy: 7d
    configuration:
        destinationPath: ENC[AES256_GCM,data:/evNksmQiKYpj4CCRW1akk3SOI7wq25b4yDEA4zOQMbGerT+fn4kzvyq0v8imGIOlb1DkOd0bC25jQj5xagT,iv:DfPs5KZP61+wo2/9AJrj8UJ8sb9wL9DN4WTkOhau5vE=,tag:tHUhaT9jrRhflapOycWaoQ==,type:str]
        s3Credentials:
            accessKeyId:
                name: aws-creds
                key: AWS_ACCESS_KEY_ID
            secretAccessKey:
                name: aws-creds
                key: AWS_SECRET_ACCESS_KEY
        wal:
            compression: gzip
        data:
            compression: ENC[AES256_GCM,data:Jen/Ew==,iv:yiFr3Xp2zyzhO+O7xr8eVgsOHAG1uFaazpqKCvDJ9Sw=,tag:fBMRETfVxgW3Zovr5RvA7Q==,type:str]
sops:
    age:
        - recipient: age1vml3vk5uzyztj96qgz7n0a6w8ynvtmxfarkp0jdl0hvcj003895qcp6z09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YVBJNGk2WDcxY2VZU0Q1
            ZmhkK0xEVmZScUpSTk1Gb0R6Qld4SklRLzNzCndyMFNnTVorMG90OVlySndMcjky
            c0lUVWt4RmkyQlhtcjRUNWV3RHQySXcKLS0tIEIySHFZMWIvVkZFVnpJcDhsR0h3
            RGpxU1BXbVY5RGZCTk56MmVFaGRsSmsKURwgdWCKrv0Mho75v5V4hiFuYa3nBu6B
            K7LqPjxYv9yefhklR+avt7+3lAN5B5jxKPJ8lw6svsni67sQbsFdyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T00:16:52Z"
    mac: ENC[AES256_GCM,data:Lb5wjzKi0/l3u4NN03zaQl/mS0kfbcVF/MnywZN3uQVWVpI4ERZG5ugLfdtrQ82hpHFPbhZ82r38JZejZM3y9x6uCHmK0Rswz1ZsHykLPZe/UfmrbIiL7gVJCLQbk4pn5LEHqjUa2a9Q8yQ5wZxmJgnn9CRG30NEzQYwe/ikwkM=,iv:I4FyBYYQoyFeazRXLQkuB/8jnOsEKJsWwpld50hhGck=,tag:88Pi3tl50VU7M84FFGlAPA==,type:str]
    encrypted_regex: ^(data|destinationPath)$
    version: 3.10.2
